export const DEFAULT_PERMISSION_NAMES = [
  'restaurant:create',
  'restaurant:update',
  'restaurant:delete',
  'restaurant:read',
  'section:create',
  'section:update',
  'section:delete',
  'section:read',
  // Reviews
  'review:create',
  'review:update',
  'review:delete',
  'review:read',
  // Reservation
  'reservation:create',
  'reservation:update',
  'reservation:delete',
  'reservation:read',
  // Tables
  'table:create',
  'table:update',
  'table:delete',
  'table:read',
  // Objects
  'object:create',
  'object:update',
  'object:delete',
  'object:read',
  // Section Objects
  'section-object:create',
  'section-object:update',
  'section-object:delete',
  'section-object:read',
] as const;

export const DEFAULT_ROLES: Array<{ name: string; permNames: string[] }> = [
  { name: 'ADMIN', permNames: [...DEFAULT_PERMISSION_NAMES] },
  {
    name: 'OWNER',
    permNames: [
      'restaurant:create',
      'restaurant:update',
      'restaurant:read',
      'section:create',
      'section:update',
      'section:read',
      'review:create',
      'review:update',
      'review:read',
      'reservation:create',
      'reservation:update',
      'reservation:read',
      'table:create',
      'table:update',
      'table:read',
      'object:create',
      'object:update',
      'object:read',
      'section-object:create',
      'section-object:update',
      'section-object:read',
    ],
  },
  {
    name: 'USER',
    permNames: [
      'restaurant:read',
      'section:read',
      'review:create',
      'review:update',
      'review:delete',
      'review:read',
      'reservation:create',
      'reservation:update',
      'reservation:delete',
      'reservation:read',
      'table:read',
      'object:read',
      'section-object:read',
    ],
  },
];
