export const DEFAULT_PERMISSION_NAMES = [
  'restaurant:create',
  'restaurant:update',
  'restaurant:delete',
  'restaurant:read',
  'section:create',
  'section:update',
  'section:delete',
  'section:read',
  // Reviews
  'review:create',
  'review:update',
  'review:delete',
  'review:read',
  // Booking
  'booking:create',
  'booking:update',
  'booking:delete',
  'booking:read',
  // Tables
  'table:create',
  'table:update',
  'table:delete',
  'table:read',
] as const;

export const DEFAULT_ROLES: Array<{ name: string; permNames: string[] }> = [
  { name: 'ADMIN', permNames: [...DEFAULT_PERMISSION_NAMES] },
  {
    name: 'OWNER',
    permNames: [
      'restaurant:create',
      'restaurant:update',
      'restaurant:read',
      'section:create',
      'section:update',
      'section:read',
      'review:create',
      'review:update',
      'review:read',
      'booking:create',
      'booking:update',
      'booking:read',
      'table:create',
      'table:update',
      'table:read',
    ],
  },
  {
    name: 'USER',
    permNames: [
      'restaurant:read',
      'section:read',
      'review:create',
      'review:update',
      'review:delete',
      'review:read',
      'booking:create',
      'booking:update',
      'booking:delete',
      'booking:read',
      'table:read',
    ],
  },
];
