
// Repositories
export const SUBSCRIPTION_ANALYTICS_REPOSITORY = Symbol(
  'SUBSCRIPTION_ANALYTICS_REPOSITORY',
);
export const SUBSCRIPTION_PLAN_ANALYTICS_REPOSITORY = Symbol(
  'SUBSCRIPTION_PLAN_ANALYTICS_REPOSITORY',
);

// Mappers
export const SUBSCRIPTION_ORM_MAPPER = Symbol('SUBSCRIPTION_ORM_MAPPER');
export const SUBSCRIPTION_PLAN_ORM_MAPPER = Symbol(
  'SUBSCRIPTION_PLAN_ORM_MAPPER',
);
