export const KAFKA_TOPICS = {
  REVIEW_CREATED: 'mesa-ya.reviews.created',
  REVIEW_UPDATED: 'mesa-ya.reviews.updated',
  REVIEW_DELETED: 'mesa-ya.reviews.deleted',
  RESTAURANT_CREATED: 'mesa-ya.restaurants.created',
  RESTAURANT_UPDATED: 'mesa-ya.restaurants.updated',
  RESTAURANT_DELETED: 'mesa-ya.restaurants.deleted',
  SECTION_CREATED: 'mesa-ya.sections.created',
  SECTION_UPDATED: 'mesa-ya.sections.updated',
  SECTION_DELETED: 'mesa-ya.sections.deleted',
  TABLE_CREATED: 'mesa-ya.tables.created',
  TABLE_UPDATED: 'mesa-ya.tables.updated',
  TABLE_DELETED: 'mesa-ya.tables.deleted',
  /** Emitted when a user temporarily selects a table during reservation flow */
  TABLE_SELECTING: 'mesa-ya.tables.selecting',
  /** Emitted when a user releases a temporarily selected table */
  TABLE_RELEASED: 'mesa-ya.tables.released',
  OBJECT_CREATED: 'mesa-ya.objects.created',
  OBJECT_UPDATED: 'mesa-ya.objects.updated',
  OBJECT_DELETED: 'mesa-ya.objects.deleted',
  MENU_CREATED: 'mesa-ya.menus.created',
  MENU_UPDATED: 'mesa-ya.menus.updated',
  MENU_DELETED: 'mesa-ya.menus.deleted',
  DISH_CREATED: 'mesa-ya.dishes.created',
  DISH_UPDATED: 'mesa-ya.dishes.updated',
  DISH_DELETED: 'mesa-ya.dishes.deleted',
  IMAGE_CREATED: 'mesa-ya.images.created',
  IMAGE_UPDATED: 'mesa-ya.images.updated',
  IMAGE_DELETED: 'mesa-ya.images.deleted',
  SECTION_OBJECT_CREATED: 'mesa-ya.section-objects.created',
  SECTION_OBJECT_UPDATED: 'mesa-ya.section-objects.updated',
  SECTION_OBJECT_DELETED: 'mesa-ya.section-objects.deleted',
  RESERVATION_CREATED: 'mesa-ya.reservations.created',
  RESERVATION_UPDATED: 'mesa-ya.reservations.updated',
  RESERVATION_DELETED: 'mesa-ya.reservations.deleted',
  PAYMENT_CREATED: 'mesa-ya.payments.created',
  PAYMENT_UPDATED: 'mesa-ya.payments.updated',
  PAYMENT_DELETED: 'mesa-ya.payments.deleted',
  SUBSCRIPTION_CREATED: 'mesa-ya.subscriptions.created',
  SUBSCRIPTION_UPDATED: 'mesa-ya.subscriptions.updated',
  SUBSCRIPTION_DELETED: 'mesa-ya.subscriptions.deleted',
  SUBSCRIPTION_PLAN_CREATED: 'mesa-ya.subscription-plans.created',
  SUBSCRIPTION_PLAN_UPDATED: 'mesa-ya.subscription-plans.updated',
  SUBSCRIPTION_PLAN_DELETED: 'mesa-ya.subscription-plans.deleted',
  AUTH_USER_SIGNED_UP: 'mesa-ya.auth.user-signed-up',
  AUTH_USER_LOGGED_IN: 'mesa-ya.auth.user-logged-in',
  AUTH_USER_ROLES_UPDATED: 'mesa-ya.auth.user-roles-updated',
  AUTH_ROLE_PERMISSIONS_UPDATED: 'mesa-ya.auth.role-permissions-updated',
  OWNER_UPGRADE_STATUS_CHANGED: 'mesa-ya.owner-upgrade.status-changed',
} as const;

export type KafkaTopic = (typeof KAFKA_TOPICS)[keyof typeof KAFKA_TOPICS];
