export const KAFKA_TOPICS = {
  REVIEW_CREATED: 'mesa-ya.reviews.created',
  REVIEW_UPDATED: 'mesa-ya.reviews.updated',
  REVIEW_DELETED: 'mesa-ya.reviews.deleted',
  RESTAURANT_CREATED: 'mesa-ya.restaurants.created',
  RESTAURANT_UPDATED: 'mesa-ya.restaurants.updated',
  RESTAURANT_DELETED: 'mesa-ya.restaurants.deleted',
  SECTION_CREATED: 'mesa-ya.sections.created',
  SECTION_UPDATED: 'mesa-ya.sections.updated',
  SECTION_DELETED: 'mesa-ya.sections.deleted',
  TABLE_CREATED: 'mesa-ya.tables.created',
  TABLE_UPDATED: 'mesa-ya.tables.updated',
  TABLE_DELETED: 'mesa-ya.tables.deleted',
  OBJECT_CREATED: 'mesa-ya.objects.created',
  OBJECT_UPDATED: 'mesa-ya.objects.updated',
  OBJECT_DELETED: 'mesa-ya.objects.deleted',
  IMAGE_CREATED: 'mesa-ya.images.created',
  IMAGE_UPDATED: 'mesa-ya.images.updated',
  IMAGE_DELETED: 'mesa-ya.images.deleted',
  SECTION_OBJECT_CREATED: 'mesa-ya.section-objects.created',
  SECTION_OBJECT_UPDATED: 'mesa-ya.section-objects.updated',
  SECTION_OBJECT_DELETED: 'mesa-ya.section-objects.deleted',
  RESERVATION_CREATED: 'mesa-ya.reservations.created',
  RESERVATION_UPDATED: 'mesa-ya.reservations.updated',
  RESERVATION_DELETED: 'mesa-ya.reservations.deleted',
} as const;

export type KafkaTopic = (typeof KAFKA_TOPICS)[keyof typeof KAFKA_TOPICS];
