// Repositories
export const GRAPHIC_OBJECT_REPOSITORY = Symbol('GRAPHIC_OBJECT_REPOSITORY');
export const GRAPHIC_OBJECT_ANALYTICS_REPOSITORY = Symbol(
  'GRAPHIC_OBJECT_ANALYTICS_REPOSITORY',
);

// Services & Adapters
export const GRAPHIC_OBJECT_EVENT_PUBLISHER = Symbol(
  'GRAPHIC_OBJECT_EVENT_PUBLISHER',
);
