/**
 * Lista de nombres de permisos por defecto del sistema.
 * Define todas las acciones CRUD disponibles para cada recurso.
 */
export const DEFAULT_PERMISSION_NAMES = [
  'restaurant:create',
  'restaurant:update',
  'restaurant:delete',
  'restaurant:read',
  'section:create',
  'section:update',
  'section:delete',
  'section:read',
  'menu:create',
  'menu:update',
  'menu:delete',
  'menu:read',
  'menu-category:create',
  'menu-category:update',
  'menu-category:delete',
  'menu-category:read',
  'dish:create',
  'dish:update',
  'dish:delete',
  'dish:read',
  'review:create',
  'review:update',
  'review:delete',
  'review:read',
  'payment:create',
  'payment:update',
  'payment:delete',
  'payment:read',
  'reservation:create',
  'reservation:update',
  'reservation:delete',
  'reservation:read',
  'table:create',
  'table:update',
  'table:delete',
  'table:read',
  'object:create',
  'object:update',
  'object:delete',
  'object:read',
  'image:create',
  'image:update',
  'image:delete',
  'image:read',
  'section-object:create',
  'section-object:update',
  'section-object:delete',
  'section-object:read',
  'subscription:create',
  'subscription:update',
  'subscription:delete',
  'subscription:read',
  'subscription-plan:create',
  'subscription-plan:update',
  'subscription-plan:delete',
  'subscription-plan:read',
] as const;

export type PermissionName = (typeof DEFAULT_PERMISSION_NAMES)[number];
