// Repositories
export const RESERVATION_REPOSITORY = Symbol('RESERVATION_REPOSITORY');
export const RESERVATION_ANALYTICS_REPOSITORY = Symbol(
  'RESERVATION_ANALYTICS_REPOSITORY',
);

// Services & Adapters
export const RESERVATION_EVENT_PUBLISHER = Symbol(
  'RESERVATION_EVENT_PUBLISHER',
);

// External Readers
export const USER_RESERVATION_READER = Symbol('USER_RESERVATION_READER');
export const RESTAURANT_RESERVATION_READER = Symbol(
  'RESTAURANT_RESERVATION_READER',
);
