

// Repositories
export const AUTH_USER_REPOSITORY = Symbol('AUTH_USER_REPOSITORY');
export const AUTH_ROLE_REPOSITORY = Symbol('AUTH_ROLE_REPOSITORY');
export const AUTH_PERMISSION_REPOSITORY = Symbol('AUTH_PERMISSION_REPOSITORY');
export const AUTH_ANALYTICS_REPOSITORY = Symbol('AUTH_ANALYTICS_REPOSITORY');

// Services
export const AUTH_TOKEN_SERVICE = Symbol('AUTH_TOKEN_SERVICE');
export const AUTH_PASSWORD_HASHER = Symbol('AUTH_PASSWORD_HASHER');
